services:
  - type: web
    name: chess-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 300 'backend.app_factory:app' --bind=0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://chess-ai-frontend.onrender.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: chess-game-state
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false

  - type: redis
    name: chess-game-state
    ipAllowList:
      - source: 0.0.0.0/0

  - type: static
    name: chess-ai-frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - vite.config.ts
    envVars:
      - key: VITE_API_URL
        value: https://chess-ai-backend.onrender.com
      - key: VITE_SOCKET_URL
        value: https://chess-ai-backend.onrender.com
