services:
  - type: web
    name: chess-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://chess-ai-frontend.onrender.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: chess-game-state
          property: connectionString

  - type: redis
    name: chess-game-state
    ipAllowList:
      - source: 0.0.0.0/0

  - type: static
    name: chess-ai-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://chess-ai-backend.onrender.com
      - key: VITE_SOCKET_URL
        value: https://chess-ai-backend.onrender.com
