services:
  - type: web
    name: chess-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && PYTHONPATH=/opt/render/project/src gunicorn 'backend.app.flask_app:app' --bind=0.0.0.0:$PORT --log-level debug
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHON_VERSION
        value: 3.11.11

  - type: static
    name: chess-ai-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
